### ISSUE TITLE
Any one run successfuly project on Ubuntu 24.04 ?

### ISSUE THREAD

**Issue by patel0712** [hlwhl/webview_cef#160]
i'm not able to run app on Ubuntu 24.04

[  +29 ms] executing: uname -m
[  +13 ms] Exit code 0 from: uname -m
[        ] x86_64
[ +127 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'LegacyCanvasKitRemover' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +84 ms] executing: /home/jeet-patel07/Android/Sdk/platform-tools/adb devices -l
[  +70 ms] List of devices attached
[  +11 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[  +12 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +138 ms] Skipping pub get: version match.
[ +108 ms] Found plugin webview_cef at /home/jeet-patel07/webview_cef/
[ +101 ms] Found plugin webview_cef at /home/jeet-patel07/webview_cef/
[ +189 ms] No packages with native assets. Skipping native assets compilation.
[   +6 ms] Initializing file store
[  +14 ms] Skipping target: gen_localizations
[   +7 ms] gen_dart_plugin_registrant: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have updated contents:
/home/jeet-patel07/webview_cef/example/.dart_tool/package_config_subset}
[  +89 ms] Found plugin webview_cef at /home/jeet-patel07/webview_cef/
[  +12 ms] gen_dart_plugin_registrant: Complete
[   +1 ms] _composite: Starting due to {}
[        ] _composite: Complete
[   +4 ms] complete
[  +10 ms] Launching lib/main.dart on Linux in debug mode...
[   +8 ms] /home/jeet-patel07/snap/flutter/common/flutter/bin/cache/dart-sdk/bin/dartaotruntime --disable-dart-dev
/home/jeet-patel07/snap/flutter/common/flutter/bin/cache/dart-sdk/bin/snapshots/frontend_server_aot.dart.snapshot --sdk-root
/home/jeet-patel07/snap/flutter/common/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --target=flutter --experimental-emit-debug-metadata
-DFLUTTER_WEB_AUTO_DETECT=true -DFLUTTER_WEB_CANVASKIT_URL=https://www.gstatic.com/flutter-canvaskit/e76c956498841e1ab458577d3892003e553e4f3c/ --output-dill
/tmp/flutter_tools.BVBAMH/flutter_tool.BPQVHW/app.dill --packages /home/jeet-patel07/webview_cef/example/.dart_tool/package_config.json -Ddart.vm.profile=false
-Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill
build/129fe64d39a60f20f40290b7a749e2dc.cache.dill.track.dill --verbosity=error --enable-experiment=alternative-invalidation-strategy
[  +37 ms] Building Linux application...
[  +14 ms] <- compile package:webview_cef_example/main.dart
[   +6 ms] executing: [build/linux/x64/debug/] cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug -DFLUTTER_TARGET_PLATFORM=linux-x64 /home/jeet-patel07/webview_cef/example/linux
[+2365 ms] -- The CXX compiler identification is Clang 10.0.0
[  +36 ms] -- Check for working CXX compiler: /snap/flutter/current/usr/bin/clang++
[ +314 ms] -- Check for working CXX compiler: /snap/flutter/current/usr/bin/clang++ -- broken
[   +1 ms] CMake Error at /snap/flutter/145/usr/share/cmake-3.16/Modules/CMakeTestCXXCompiler.cmake:53 (message):
[   +3 ms]   The C++ compiler
[        ]     "/snap/flutter/current/usr/bin/clang++"
[        ]   is not able to compile a simple test program.
[        ]   It fails with the following output:
[        ]     Change Dir: /home/jeet-patel07/webview_cef/example/build/linux/x64/debug/CMakeFiles/CMakeTmp
[        ]     Run Build Command(s):/snap/flutter/current/usr/bin/ninja cmTC_df7f8 && [1/2] Building CXX object CMakeFiles/cmTC_df7f8.dir/testCXXCompiler.cxx.o
[        ]     [2/2] Linking CXX executable cmTC_df7f8
[        ]     FAILED: cmTC_df7f8 
[        ]     : && /snap/flutter/current/usr/bin/clang++    -B/snap/flutter/current/usr/lib/gcc/x86_64-linux-gnu/9 -B/snap/flutter/current/usr/lib/x86_64-linux-gnu
-B/snap/flutter/current/lib/x86_64-linux-gnu -B/snap/flutter/current/usr/lib/ -L/snap/flutter/current/usr/lib/gcc/x86_64-linux-gnu/9
-L/snap/flutter/current/usr/lib/x86_64-linux-gnu -L/snap/flutter/current/lib/x86_64-linux-gnu -L/snap/flutter/current/usr/lib/ -lblkid -lgcrypt -llzma -llz4 -lgpg-error
-luuid -lpthread -ldl -lepoxy -lfontconfig CMakeFiles/cmTC_df7f8.dir/testCXXCompiler.cxx.o  -o cmTC_df7f8   && :
[   +2 ms]     /snap/flutter/current/usr/bin/ld: /lib/x86_64-linux-gnu/libfreetype.so.6: undefined reference to `fstat@GLIBC_2.33'
[        ]     /snap/flutter/current/usr/bin/ld: /lib/x86_64-linux-gnu/libexpat.so.1: undefined reference to `arc4random_buf@GLIBC_2.36'
[        ]     /snap/flutter/current/usr/bin/ld: /lib/x86_64-linux-gnu/libexpat.so.1: undefined reference to `__isoc23_strtoul@GLIBC_2.38'
[        ]     clang: error: linker command failed with exit code 1 (use -v to see invocation)
[        ]     ninja: build stopped: subcommand failed.
[        ]   CMake will not be able to correctly generate this project.
[        ] Call Stack (most recent call first):
[        ]   CMakeLists.txt:3 (project)
[        ] -- Configuring incomplete, errors occurred!
[        ] See also "/home/jeet-patel07/webview_cef/example/build/linux/x64/debug/CMakeFiles/CMakeOutput.log".
[        ] See also "/home/jeet-patel07/webview_cef/example/build/linux/x64/debug/CMakeFiles/CMakeError.log".
[  +64 ms] Building Linux application... (completed in 2,794ms)
[+6418 ms] Error: Unable to generate build files
[   +3 ms] "flutter run" took 10,221ms.
[   +7 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:815:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1389:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:355:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:295:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:119:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>
           
           
[ +192 ms] ensureAnalyticsSent: 190ms
[        ] Running 1 shutdown hook
[  +11 ms] Shutdown hooks complete
[        ] exiting with code 1

**Comment by cadivus** [comment]
Maybe,it is because of you're using a Snap installation of Flutter. Did you try to install it directly as described here?:  
https://github.com/hlwhl/webview_cef/blob/bc445974dd165a527615ed152706be333c93b4b3/.github/workflows/test_linux_x86.yaml#L35


You also need some packages for compilation, you can copy the apt command from the test workflow:  
https://github.com/hlwhl/webview_cef/blob/bc445974dd165a527615ed152706be333c93b4b3/.github/workflows/test_linux_x86.yaml#L35

**Comment by patel0712** [comment]
hello @cadivus can you help me to get this
i tried to implement URL interception or we can say that Navigation Delegate feature but don't know why its not working proprly.

please check this my fork in this i have added changes related to NavigationDelegate.
https://github.com/patel0712/webview_cef

please check this and help me if possible.

**Comment by jeet-flutter10** [comment]
@hlwhl @SinyimZhi 
i create linux app bundle and when run in system in which nvidia graphics card is embedded  and i check gpu usgae 
so i know that its using nearly 1gb of gpu  so is there any way we can optimize it or any modification that helps.

**Comment by hlwhl** [comment]
> @hlwhl @SinyimZhi i create linux app bundle and when run in system in which nvidia graphics card is embedded and i check gpu usgae so i know that its using nearly 1gb of gpu so is there any way we can optimize it or any modification that helps.

Have you tried with chrome open the same pages?

**Comment by jeet-flutter10** [comment]
yes but there are normal all things.
also first i use desktop_webview_window in that its also normal resource usage like 100mb gpu and sometimes 150mb not more then that.

**Comment by jeet-flutter10** [comment]
inside webview_app.h file i see there's code related gpu can you explain what is that? is it able to fix my issue.
also if possible then guide me for my gpu issue or how can i move app process to cpu instead of gpu.

**Comment by hlwhl** [comment]
The original Ubuntu 24.04 build question is now covered by CI: v0.6.1 completes the full Linux example build on Ubuntu 24.04. Closing as completed. The later navigation and GPU-usage discussions are separate topics and should be tracked in focused issues if still relevant.
